language: objective-c
osx_image: xcode611
before_install: true
install: brew install xctester
script: make test
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
branches:
  except:
    - swift1p2
